require('dotenv').config();

const bcrypt = require('bcrypt');
const { sequelize, User, Team, TeamMember, Task } = require('../models');

async function run() {
  try {
    await sequelize.authenticate();
    await sequelize.sync();

    const passwordHash = await bcrypt.hash('SecurePass123!', 10);

    const [owner] = await User.findOrCreate({
      where: { email: 'owner@taskmaster.dev' },
      defaults: {
        name: 'Team Owner',
        passwordHash
      }
    });

    const [member] = await User.findOrCreate({
      where: { email: 'member@taskmaster.dev' },
      defaults: {
        name: 'Team Member',
        passwordHash
      }
    });

    const [team] = await Team.findOrCreate({
      where: { name: 'Core Team' },
      defaults: { description: 'Seeded team', ownerId: owner.id }
    });

    await TeamMember.findOrCreate({
      where: { teamId: team.id, userId: owner.id },
      defaults: { role: 'owner' }
    });

    await TeamMember.findOrCreate({
      where: { teamId: team.id, userId: member.id },
      defaults: { role: 'member' }
    });

    await Task.findOrCreate({
      where: { title: 'Seed task', createdBy: owner.id },
      defaults: {
        description: 'This task is generated by db:seed',
        status: 'open',
        createdBy: owner.id,
        assignedTo: member.id,
        teamId: team.id
      }
    });

    console.log('Database seed completed successfully.');
    process.exit(0);
  } catch (error) {
    console.error('Database seed failed.', error);
    process.exit(1);
  }
}

run();
